version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "KHALIL-P-JACKSON"
    assignees:
      - "KHALIL-P-JACKSON"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "KHALIL-P-JACKSON"
    assignees:
      - "KHALIL-P-JACKSON"
    commit-message:
      prefix: "ci"
      include: "scope"